fixed some comments in order to be coherent with docs
I fixed some comments in order to be coherent with symfony docs and with the output produced when some configuration is missing.
E.g. 
    Error: Cannot determine how to prefix the keys in manifest.json. Call Encore.setManifestKeyPrefix() to choose what path (e.g. build/) to use when building your manifes  t keys. This is happening because you passed an absolute URL to setPublicPath().